In [1]:
import pandas as pd

# 函数：加载GMT
def load_gmt(file_path):
    data = []
    with open(file_path, 'r') as f:
        for line in f:
            parts = line.strip().split('\t')
            set_name = parts[0]
            genes = parts[2:]
            for gene in genes:
                data.append({'set_name': set_name, 'gene': gene})
    return pd.DataFrame(data)

# 示例：加载并过滤
keywords = ['aml', 'leukemia', 'myeloid', 'transcription', 'regulation', 'runx1', 'cebpa']
df = load_gmt('c3.tft.v2023.1.Hs.symbols.gmt')  # 替换你的文件
aml_df = df[df['set_name'].str.lower().str.contains('|'.join(keywords))]

# 提取独特基因
unique_genes = aml_df['gene'].unique()
unique_df = pd.DataFrame({'gene_name': unique_genes})

# 保存
unique_df.to_csv('msigdb_aml_genes.csv', index=False)
print(unique_df.head(10))  # 检查

  gene_name
0   SLC36A2
1   SLC44A4
2      AQP9
3      OSMR
4      EDN2
5       FST
6     LEMD2
7    HNRNPR
8   SYNCRIP
9     FSTL1

In [10]:
import pandas as pd

# 函数：加载GMT
def load_gmt(file_path):
    data = []
    with open(file_path, 'r') as f:
        for line in f:
            parts = line.strip().split('\t')
            set_name = parts[0]
            genes = parts[2:]
            for gene in genes:
                data.append({'set_name': set_name, 'gene': gene})
    return pd.DataFrame(data)

# 示例：加载并过滤
keywords = ['aml', 'leukemia', 'myeloid', 'transcription', 'regulation', 'runx1', 'cebpa']
df = load_gmt('c5.go.bp.v2023.1.Hs.symbols.gmt')  # 替换你的文件
aml_df = df[df['set_name'].str.lower().str.contains('|'.join(keywords))]

# 提取独特基因
unique_genes = aml_df['gene'].unique()
unique_df1 = pd.DataFrame({'gene_name': unique_genes})

In [11]:
unique_df1

      gene_name
0         PARP3
1         ACTR2
2         RAD50
3        ALYREF
4        MAD2L2
...         ...
11003      CBR1
11004    ZNF277
11005      TERC
11006     YPEL3
11007  C1orf115

[11008 rows x 1 columns]

In [16]:
set(unique_df1['gene_name']) & set(unique_df['gene_name'])

{'ABCD4',
 'ACIN1',
 'ACSL5',
 'ACVR2A',
 'ADAMTS8',
 'ADD1',
 'ADRB2',
 'AFF2',
 'AGO1',
 'AKT2',
 'ANGPT2',
 'ANK3',
 'ANKRD1',
 'ANXA8',
 'APLNR',
 'ARF6',
 'ARHGAP12',
 'ARHGAP21',
 'ARHGAP25',
 'ARHGAP27',
 'ARHGAP30',
 'ARHGAP32',
 'ARHGAP4',
 'ARHGAP42',
 'ARHGAP45',
 'ARHGAP8',
 'ARHGEF2',
 'ARID1B',
 'ARNT',
 'ARRDC3',
 'ARRDC4',
 'ASAH2',
 'ASCL2',
 'ATF7IP',
 'ATN1',
 'ATP2A2',
 'ATP5F1A',
 'ATP6V0A1',
 'ATP6V0B',
 'AZIN1',
 'B2M',
 'BACH1',
 'BATF',
 'BATF3',
 'BCAR3',
 'BCL2A1',
 'BCL2L13',
 'BCL6',
 'BCL9L',
 'BDNF',
 'BGLAP',
 'BIRC3',
 'BLK',
 'BLOC1S1',
 'BLOC1S2',
 'BMF',
 'BMP7',
 'BMPR1B',
 'BOC',
 'BTG4',
 'C2CD5',
 'CACNA1D',
 'CACNB2',
 'CADM1',
 'CALCOCO1',
 'CALR',
 'CAMP',
 'CAP1',
 'CARMIL3',
 'CASK',
 'CAV1',
 'CBL',
 'CBX4',
 'CBX6',
 'CCDC88B',
 'CCL2',
 'CCL3',
 'CCL4',
 'CCN1',
 'CCN5',
 'CCNT2',
 'CCR1',
 'CD101',
 'CD109',
 'CD19',
 'CD1D',
 'CD28',
 'CD36',
 'CD53',
 'CD55',
 'CD6',
 'CD79B',
 'CDC37L1',
 'CDC42SE1',
 'CDK17',
 'CDKL5',
 'CDYL',
 'CEACAM1',
 'CELF1',
 'CEMIP',
 'CFAP20',
 'CFH',
 'CFL2',
 'CFP',
 'CHAD',
 'CHMP1B',
 'CHRNA10',
 'CIITA',
 'CIPC',
 'CIRBP',
 'CITED1',
 'CLDN10',
 'CLDN4',
 'CLOCK',
 'CNIH3',
 'CNTD1',
 'COA3',
 'COL4A2',
 'COLEC10',
 'CORO1C',
 'CPNE1',
 'CREB5',
 'CREM',
 'CRIM1',
 'CRTC2',
 'CRY1',
 'CSDE1',
 'CSF2',
 'CSK',
 'CSMD3',
 'CSNK1E',
 'CTDSPL2',
 'CTHRC1',
 'CTNNA3',
 'CTNNB1',
 'CTSK',
 'CTSZ',
 'CXCR3',
 'CXCR5',
 'CYBA',
 'CYGB',
 'CYP17A1',
 'CYTIP',
 'DAAM1',
 'DAB1',
 'DAB2',
 'DAB2IP',
 'DACT1',
 'DDX39B',
 'DEFB1',
 'DGKA',
 'DGKZ',
 'DIABLO',
 'DKK1',
 'DLX1',
 'DLX5',
 'DMP1',
 'DNASE1L3',
 'DNM3',
 'DNMT1',
 'DOK2',
 'DRAM2',
 'DTX1',
 'DUSP1',
 'DUSP2',
 'DYNLL1',
 'DYRK1B',
 'EBI3',
 'ECE1',
 'EDC4',
 'EDN2',
 'EGFR',
 'EGR2',
 'EHF',
 'EIF2B3',
 'EIF4ENIF1',
 'EIF5A',
 'EN1',
 'ENTPD1',
 'EP300',
 'EPB41L3',
 'EREG',
 'ERG',
 'ERLIN1',
 'ESR1',
 'ETF1',
 'EVL',
 'EYA1',
 'F5',
 'F8',
 'FAIM2',
 'FBN2',
 'FBXO11',
 'FBXW7',
 'FCER1G',
 'FCER2',
 'FCHO1',
 'FCMR',
 'FCRL3',
 'FES',
 'FGD1',
 'FGD3',
 'FGD4',
 'FGF4',
 'FGFR1',
 'FGFRL1',
 'FKTN',
 'FLI1',
 'FLT1',
 'FOXD2',
 'FOXF2',
 'FOXN3',
 'FOXP2',
 'FOXP3',
 'FRMD4A',
 'FRMD5',
 'FST',
 'FSTL1',
 'FUNDC2',
 'GABRA6',
 'GADD45B',
 'GAREM1',
 'GATA4',
 'GDPD2',
 'GFI1',
 'GPBP1L1',
 'GPC4',
 'GPD1',
 'GPER1',
 'GPR137B',
 'GPR171',
 'GPR18',
 'GPSM3',
 'GPX1',
 'GRAP2',
 'GRHL3',
 'GRIN2D',
 'GRK5',
 'GSAP',
 'GSDME',
 'GTF2A1',
 'GZMB',
 'H3-3B',
 'HAPLN3',
 'HCAR2',
 'HDAC7',
 'HDGF',
 'HEMGN',
 'HES1',
 'HEY1',
 'HHIP',
 'HINFP',
 'HIPK1',
 'HIVEP3',
 'HLA-DMB',
 'HLX',
 'HOXA9',
 'HOXB1',
 'HOXB3',
 'HOXB4',
 'HOXB5',
 'HOXB6',
 'HOXB7',
 'HOXB9',
 'HOXC4',
 'HOXD10',
 'HP1BP3',
 'HSP90B1',
 'HTR2C',
 'HTR3A',
 'HTRA4',
 'ID3',
 'IFNG',
 'IGKC',
 'IL13',
 'IL16',
 'IL17A',
 'IL17B',
 'IL17F',
 'IL18RAP',
 'IL19',
 'IL1RAPL1',
 'IL23A',
 'IL3',
 'IL4I1',
 'IL7R',
 'INPPL1',
 'INTS3',
 'IRF8',
 'ISG15',
 'JARID2',
 'JDP2',
 'JMJD1C',
 'JPH1',
 'JUP',
 'KCNJ1',
 'KCNJ13',
 'KCNJ16',
 'KCNJ2',
 'KCNN4',
 'KIF18B',
 'KIF2B',
 'KLHL20',
 'KLK3',
 'KMT2A',
 'KMT2E',
 'LARS1',
 'LCK',
 'LCOR',
 'LDLRAD4',
 'LEMD2',
 'LFNG',
 'LIF',
 'LIFR',
 'LIMK2',
 'LMO2',
 'LMO3',
 'LMO4',
 'LPAR5',
 'LRP5',
 'LTBP1',
 'LTBP3',
 'LUC7L',
 'LY86',
 'LY9',
 'LYPD1',
 'LZTFL1',
 'MACROH2A1',
 'MADD',
 'MAFG',
 'MAOA',
 'MAP2K3',
 'MAP2K6',
 'MAP3K11',
 'MAPRE2',
 'MATN1',
 'MBNL1',
 'MCTP1',
 'MEIS2',
 'MEMO1',
 'MEOX2',
 'MIR137HG',
 'MIR155HG',
 'MIR17HG',
 'MIR384',
 'MITF',
 'MKLN1',
 'MKNK2',
 'MLLT11',
 'MME',
 'MMP14',
 'MMP9',
 'MOAP1',
 'MOB3A',
 'MOSPD2',
 'MPL',
 'MPO',
 'MR1',
 'MRTFA',
 'MS4A1',
 'MSI2',
 'MTMR3',
 'MTMR4',
 'MTTP',
 'MTX1',
 'MXI1',
 'MYO1C',
 'MYOD1',
 'MYRF',
 'MZB1',
 'NANOS3',
 'NAPA',
 'NAPG',
 'NAV3',
 'NEDD9',
 'NEK10',
 'NEK6',
 'NEK8',
 'NEUROG2',
 'NFAT5',
 'NFATC1',
 'NFRKB',
 'NKX2-1',
 'NLRP3',
 'NOTCH1',
 'NOTCH2',
 'NOTCH2NLA',
 'NPVF',
 'NR0B2',
 'NR2F2',
 'NR3C1',
 'NR3C2',
 'NR4A1',
 'NRAS',
 'NREP',
 'NRP2',
 'NRXN1',
 'NSD3',
 'NSMCE3',
 'NXN',
 'ODAPH',
 'OLIG3',
 'ONECUT2',
 'OPA3',
 'OSCAR',
 'OSMR',
 'OTP',
 'OTUD5',
 'OTX1',
 'OTX2',
 'P2RX1',
 'P2RX5',
 'P2RY10',
 'PAFAH1B1',
 'PAN2',
 'PASK',
 'PAX6',
 'PBK',
 'PBX1',
 'PCF11',
 'PCGF6',
 'PCSK2',
 'PCSK4',
 'PCSK5',
 'PDE3B',
 'PDE4D',
 'PDE6H',
 'PDGFB',
 'PDGFC',
 'PDP1',
 'PDSS2',
 'PDZK1',
 'PER1',
 'PGF',
 'PHF21A',
 'PHF6',
 'PI15',
 'PICALM',
 'PIK3AP1',
 'PIK3R1',
 'PLA2G4A',
 'PLEK',
 'PLEKHA2',
 'PLEKHG2',
 'PLXNC1',
 'POLG2',
 'POLR1F',
 'POU2AF1',
 'POU2F1',
 'PPARG',
 'PPP1CB',
 'PPP1R14C',
 'PPP3CB',
 'PRDM1',
 'PRICKLE1',
 'PRKACA',
 'PRKAG1',
 'PRKCH',
 'PROK2',
 'PROS1',
 'PRR5L',
 'PRUNE1',
 'PSMA1',
 'PTCH1',
 'PTGR3',
 'PTK2',
 'PTK2B',
 'PTPA',
 'PTPN22',
 'PTPRS',
 'PUM2',
 'PUS10',
 'PXN',
 'PYM1',
 'RAB39A',
 'RAB3IP',
 'RAB5B',
 'RABGAP1L',
 'RAG1',
 'RAMP2',
 'RARB',
 'RASAL2',
 'RASGEF1A',
 'RASGRP2',
 'RASGRP3',
 'RASSF2',
 'RB1CC1',
 'RBBP4',
 'RBBP6',
 'RBL1',
 'RBM14',
 'RBM4',
 'RC3H2',
 'RCC2',
 'RCOR1',
 'RCOR2',
 'RDH5',
 'REL',
 'RESF1',
 'RGMA',
 'RGN',
 'RGS1',
 'RGS14',
 'RGS18',
 'RGS20',
 'RHBDF2',
 'RHEX',
 'RHOG',
 'RHOQ',
 'RILPL1',
 'RIMS2',
 'RNF19B',
 'RNF207',
 'RNF220',
 'RNF40',
 'RNF43',
 'ROGDI',
 'RORC',
 'RPA3',
 'RTN4RL1',
 'RUNX1',
 'RUNX2',
 'RUNX3',
 'RUVBL2',
 'RYBP',
 'S100A9',
 'S1PR1',
 'S1PR2',
 'SALL1',
 'SAMD7',
 'SASH3',
 'SCAI',
 'SCEL',
 'SCN2B',
 'SCN3B',
 'SCN8A',
 'SCNN1A',
 'SCRN1',
 'SDF2L1',
 'SEC14L1',
 'SEMA4A',
 'SEPTIN9',
 'SERPINA7',
 'SFRP2',
 'SGIP1',
 'SH2D3C',
 'SH3BP1',
 'SH3BP5L',
 'SHANK2',
 'SHKBP1',
 'SHOX2',
 'SIAH3',
 'SIPA1',
 'SIRPA',
 'SIRT1',
 'SIRT6',
 'SLA',
 'SLA2',
 'SLC12A1',
 'SLC12A6',
 'SLC15A3',
 'SLC24A1',
 'SLC25A12',
 'SLC31A2',
 'SLC43A2',
 'SLC44A4',
 'SLC4A5',
 'SLC6A9',
 'SLITRK1',
 'SLITRK5',
 'SMAD6',
 'SMARCA2',
 'SMG7',
 'SNX1',
 'SNX25',
 'SOST',
 'SOX11',
 'SOX5',
 'SP3',
 'SP6',
 'SPDEF',
 'SPIB',
 'SPINK6',
 'SPRED1',
 'SPTLC2',
 'SREBF2',
 'SRSF2',
 'SRSF4',
 'SSH3',
 'ST3GAL1',
 'ST6GAL1',
 'STAT2',
 'STAU1',
 'STC1',
 'STN1',
 'STON1',
 'SULF1',
 'SUPT16H',
 'SUPT4H1',
 'SYNCRIP',
 'SYNJ1',
 'SYT9',
 'SYVN1',
 'TACSTD2',
 'TAGAP',
 'TAMALIN',
 'TBC1D10B',
 'TBC1D16',
 'TBK1',
 'TBL1X',
 'TBPL1',
 'TBR1',
 'TBRG4',
 'TBX5',
 'TBX6',
 'TCF12',
 'TCF7',
 'TCF7L1',
 'TET3',
 'TFEB',
 'THRA',
 'TLCD1',
 'TLE4',
 'TLL2',
 'TLN1',
 'TLR1',
 'TLR8',
 'TLR9',
 'TLX2',
 'TMEM109',
 'TMEM215',
 'TMEM37',
 'TNFRSF12A',
 'TNFSF11',
 'TNFSF13',
 'TNFSF13B',
 'TNFSF4',
 'TNNT2',
 'TNR',
 'TNS2',
 'TOB1',
 'TOR1AIP1',
 'TP63',
 'TPM1',
 'TRIB1',
 'TRIM37',
 'TRIM38',
 'TRIM8',
 'TRPM8',
 'TRPV2',
 'TSC22D1',
 'TSC22D3',
 'TSPAN13',
 'TSPAN32',
 'TSPYL2',
 'TSSK2',
 'TWF1',
 'TXLNG',
 'TXNDC12',
 'TXNIP',
 'UBAC2',
 'UBE2E2',
 'USP34',
 'USP5',
 'USP7',
 'USP9X',
 'VASN',
 'VIM',
 'VRK1',
 'WAS',
 'WDR81',
 'WNK4',
 'WNT10B',
 'WNT5A',
 'WNT7B',
 'XCL1',
 'XCL2',
 'XK',
 'YBX2',
 'ZBTB18',
 'ZBTB20',
 'ZBTB25',
 'ZBTB8A',
 'ZEB1',
 'ZEB2',
 'ZEB2-AS1',
 'ZFAT',
 'ZFHX3',
 'ZIC2',
 'ZMYND8',
 'ZNF398'}

In [17]:
aml_df

                                                set_name    gene
1550                GOBP_REGULATION_OF_DNA_RECOMBINATION   PARP3
1551                GOBP_REGULATION_OF_DNA_RECOMBINATION   ACTR2
1552                GOBP_REGULATION_OF_DNA_RECOMBINATION   RAD50
1553                GOBP_REGULATION_OF_DNA_RECOMBINATION  ALYREF
1554                GOBP_REGULATION_OF_DNA_RECOMBINATION  MAD2L2
...                                                  ...     ...
642640  GOBP_REGULATION_OF_CAVEOLIN_MEDIATED_ENDOCYTOSIS   PROM2
642641  GOBP_REGULATION_OF_CAVEOLIN_MEDIATED_ENDOCYTOSIS  NEDD4L
642642  GOBP_REGULATION_OF_CAVEOLIN_MEDIATED_ENDOCYTOSIS     SRC
642643  GOBP_REGULATION_OF_CAVEOLIN_MEDIATED_ENDOCYTOSIS    CAV3
642644  GOBP_REGULATION_OF_CAVEOLIN_MEDIATED_ENDOCYTOSIS  UNC119

[235303 rows x 2 columns]